name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: true
      age:
        description: "Your age"
        required: true

jobs:
  dynamic-input-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Debug Inputs
        run: |
          echo 'Input :'
          echo '${{ toJson(inputs) }}'

      - name: Run Python Script
        run: |
          echo '${{ toJson(inputs) }}' > input.json
          python sample.py input.json
