name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: true
      age:
        description: "Your age"
        required: true

jobs:
  dynamic-input-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Script
        run: python sample.py "${{ toJson(inputs) }}"
